# .NET Desktop
# Build and run tests for .NET Desktop or Windows classic desktop solutions.
# Add steps that publish symbols, save build artifacts, and more:
# https://docs.microsoft.com/azure/devops/pipelines/apps/windows/dot-net

trigger:
- master

pool:
  vmImage: 'windows-latest'

variables:
  solutionDir: 'Software\OpenAstroTracker ASCOM'
  solution: '$(solutionDir)\OpenAstroTracker.sln'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'

steps:
- task: NuGetToolInstaller@1

- task: NuGetCommand@2
  inputs:
    command: 'restore'
    restoreSolution: '$(solutionDir)\OpenAstroTracker\packages.config'
    feedsToUse: 'select'
    restoreDirectory: 'packages'

- task: NuGetCommand@2
  inputs:
    command: 'restore'
    restoreSolution: '$(solutionDir)\TelescopeDriver\packages.config'
    feedsToUse: 'select'
    restoreDirectory: 'packages'


- task: VSBuild@1
  inputs:
    solution: '$(solution)'
    msbuildArgs: 'ToolPath=$(solutionDir)\packages'
    platform: '$(buildPlatform)'
    configuration: '$(buildConfiguration)'

- task: CmdLine@2
  inputs:
    script: '$(solutionDir)\OpenAstroTracker\packages\Tools.InnoSetup*\tools\ISCC.exe /F "OpenAstroTracker ASCOM" "$(solutionDir)\OpenAstroTracker Setup.iss"'

- task: VSTest@2
  inputs:
    platform: '$(buildPlatform)'
    configuration: '$(buildConfiguration)'
